### ISSUE TITLE
Required BIOS Files for Cores

### ISSUE THREAD

**Issue by chiaroscurosity** [OpenEmu/Higan-Core#1]
Hello,

I am searching for a repository of all BIOS files that are required by the cores. First, I am wondering if it is legal to keep the cores all in one location. My goal is to make it easier for someone like me to add the BIOS files without having to do a lot of digging. For example, I compiled the three BIOS files for Playstation from doing an Internet search. After a few trial and error attempts, I found a blog post that helped me through one of the BIOS files that was not labeled correctly. Once that was fixed then I got a game to launch okay. I am struggling to locate the BIOS for Odyssey. I can't find it online anywhere.

Has anyone gone through this process and obtained all the BIOS files? If so, can I get them from you? Thanks for any assistance. The list of files is here [https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files](https://github.com/OpenEmu/OpenEmu/wiki/User-guide:-BIOS-files)

**Comment by clobber** [comment]
You are on your own. We're not posting copy infringing files here or linking to them.
